/*
 * Na calculadora foi incorporado um pequeno menu de configuração para
 * melhor experiência do usuário. 
*/
package calculadora;

import java.awt.Color;
import java.awt.Font;


public class Calculadora extends javax.swing.JFrame {

    public Calculadora() {
        initComponents();
        setTitle("Calculadora");
        setLocationRelativeTo(null);
        setResizable(false);
    }
        
    int resetar;
    double num1, num2;
    String operador;

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Button0 = new javax.swing.JButton();
        ButtonSub = new javax.swing.JButton();
        ButtonMulti = new javax.swing.JButton();
        ButtonSoma = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        ButtonC = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        ButtonCe = new javax.swing.JButton();
        ButtonDiv = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        ButtonDot = new javax.swing.JButton();
        TxtCalc = new javax.swing.JTextField();
        Button1 = new javax.swing.JButton();
        LabelTitulo = new javax.swing.JLabel();
        ButtonIgual = new javax.swing.JButton();
        ButtonSqrt = new javax.swing.JButton();
        ButtonPow = new javax.swing.JButton();
        ButtonNegative = new javax.swing.JButton();
        ButtonPorcento = new javax.swing.JButton();
        ButtonDel = new javax.swing.JButton();
        LabelCredito = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        MenuTema = new javax.swing.JMenu();
        TemaClaro = new javax.swing.JCheckBoxMenuItem();
        TemaEscuro = new javax.swing.JCheckBoxMenuItem();
        TemaFontes = new javax.swing.JMenu();
        FonteTahoma = new javax.swing.JCheckBoxMenuItem();
        FonteArial = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Button0.setBackground(new java.awt.Color(204, 204, 204));
        Button0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button0.setText("0");
        Button0.setBorder(null);
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });

        ButtonSub.setBackground(new java.awt.Color(153, 204, 255));
        ButtonSub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonSub.setText("-");
        ButtonSub.setBorder(null);
        ButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubActionPerformed(evt);
            }
        });

        ButtonMulti.setBackground(new java.awt.Color(153, 204, 255));
        ButtonMulti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonMulti.setText("x");
        ButtonMulti.setBorder(null);
        ButtonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiActionPerformed(evt);
            }
        });

        ButtonSoma.setBackground(new java.awt.Color(153, 204, 255));
        ButtonSoma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonSoma.setText("+");
        ButtonSoma.setBorder(null);
        ButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSomaActionPerformed(evt);
            }
        });

        Button2.setBackground(new java.awt.Color(204, 204, 204));
        Button2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button2.setText("2");
        Button2.setBorder(null);
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Button5.setBackground(new java.awt.Color(204, 204, 204));
        Button5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button5.setText("5");
        Button5.setBorder(null);
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        ButtonC.setBackground(new java.awt.Color(153, 204, 255));
        ButtonC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonC.setText("C");
        ButtonC.setBorder(null);
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });

        Button6.setBackground(new java.awt.Color(204, 204, 204));
        Button6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button6.setText("6");
        Button6.setBorder(null);
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        ButtonCe.setBackground(new java.awt.Color(153, 204, 255));
        ButtonCe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonCe.setText("CE");
        ButtonCe.setBorder(null);
        ButtonCe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCeActionPerformed(evt);
            }
        });

        ButtonDiv.setBackground(new java.awt.Color(153, 204, 255));
        ButtonDiv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonDiv.setText("÷");
        ButtonDiv.setBorder(null);
        ButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivActionPerformed(evt);
            }
        });

        Button9.setBackground(new java.awt.Color(204, 204, 204));
        Button9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button9.setText("9");
        Button9.setBorder(null);
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button8.setBackground(new java.awt.Color(204, 204, 204));
        Button8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button8.setText("8");
        Button8.setBorder(null);
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button7.setBackground(new java.awt.Color(204, 204, 204));
        Button7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button7.setText("7");
        Button7.setBorder(null);
        Button7.setBorderPainted(false);
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button3.setBackground(new java.awt.Color(204, 204, 204));
        Button3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button3.setText("3");
        Button3.setBorder(null);
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        Button4.setBackground(new java.awt.Color(204, 204, 204));
        Button4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button4.setText("4");
        Button4.setBorder(null);
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        ButtonDot.setBackground(new java.awt.Color(204, 204, 204));
        ButtonDot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonDot.setText(".");
        ButtonDot.setBorder(null);
        ButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDotActionPerformed(evt);
            }
        });

        TxtCalc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TxtCalc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCalcActionPerformed(evt);
            }
        });

        Button1.setBackground(new java.awt.Color(204, 204, 204));
        Button1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button1.setText("1");
        Button1.setBorder(null);
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        LabelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        LabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitulo.setText("CALCULADORA");

        ButtonIgual.setBackground(new java.awt.Color(0, 153, 204));
        ButtonIgual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonIgual.setText("=");
        ButtonIgual.setBorder(null);
        ButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIgualActionPerformed(evt);
            }
        });

        ButtonSqrt.setBackground(new java.awt.Color(153, 204, 255));
        ButtonSqrt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonSqrt.setText("√");
        ButtonSqrt.setBorder(null);
        ButtonSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSqrtActionPerformed(evt);
            }
        });

        ButtonPow.setBackground(new java.awt.Color(153, 204, 255));
        ButtonPow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonPow.setText("xⁿ");
        ButtonPow.setBorder(null);
        ButtonPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPowActionPerformed(evt);
            }
        });

        ButtonNegative.setBackground(new java.awt.Color(153, 204, 255));
        ButtonNegative.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonNegative.setText("+/-");
        ButtonNegative.setBorder(null);
        ButtonNegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNegativeActionPerformed(evt);
            }
        });

        ButtonPorcento.setBackground(new java.awt.Color(153, 204, 255));
        ButtonPorcento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonPorcento.setText("%");
        ButtonPorcento.setBorder(null);
        ButtonPorcento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPorcentoActionPerformed(evt);
            }
        });

        ButtonDel.setBackground(new java.awt.Color(153, 204, 255));
        ButtonDel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ButtonDel.setText("⌫");
        ButtonDel.setBorder(null);
        ButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonSoma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonNegative, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPorcento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ButtonCe, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtCalc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonPow, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(LabelTitulo)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCe, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPow, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ButtonIgual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonNegative, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonPorcento, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        LabelCredito.setBackground(new java.awt.Color(0, 0, 0));
        LabelCredito.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelCredito.setForeground(new java.awt.Color(255, 255, 255));
        LabelCredito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCredito.setText("Desenvolvido por Gabriel Baseggio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(LabelCredito, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        Menu.setText("Configurações");

        MenuTema.setText("Temas");

        TemaClaro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        TemaClaro.setText("Tema Claro");
        TemaClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemaClaroActionPerformed(evt);
            }
        });
        MenuTema.add(TemaClaro);

        TemaEscuro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        TemaEscuro.setSelected(true);
        TemaEscuro.setText("Tema Escuro");
        TemaEscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemaEscuroActionPerformed(evt);
            }
        });
        MenuTema.add(TemaEscuro);

        Menu.add(MenuTema);

        TemaFontes.setText("Fontes");

        FonteTahoma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        FonteTahoma.setSelected(true);
        FonteTahoma.setText("Tahoma");
        FonteTahoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FonteTahomaActionPerformed(evt);
            }
        });
        TemaFontes.add(FonteTahoma);

        FonteArial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        FonteArial.setText("Cambria");
        FonteArial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FonteArialActionPerformed(evt);
            }
        });
        TemaFontes.add(FonteArial);

        Menu.add(TemaFontes);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCalcActionPerformed
        
    }//GEN-LAST:event_TxtCalcActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        if(resetar == 1){
            TxtCalc.setText("");
        }
        TxtCalc.setText(TxtCalc.getText() + "0");
        resetar = 0;
    }//GEN-LAST:event_Button0ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        if(resetar == 1){
            TxtCalc.setText("");
        }
        TxtCalc.setText(TxtCalc.getText() + "1");
        resetar = 0;
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        if(resetar == 1){
            TxtCalc.setText("");
        }
        TxtCalc.setText(TxtCalc.getText() + "2");
        resetar = 0;
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        if(resetar == 1){
            TxtCalc.setText("");
        }
        TxtCalc.setText(TxtCalc.getText() + "3");
        resetar = 0;
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        if(resetar == 1){
            TxtCalc.setText("");
        }
        TxtCalc.setText(TxtCalc.getText() + "4");
        resetar = 0;
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        if(resetar == 1){
            TxtCalc.setText("");
        }
        TxtCalc.setText(TxtCalc.getText() + "5");
        resetar = 0;
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        if(resetar == 1){
            TxtCalc.setText("");
        }
        TxtCalc.setText(TxtCalc.getText() + "6");
        resetar = 0;
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        if(resetar == 1){
            TxtCalc.setText("");
        }
        TxtCalc.setText(TxtCalc.getText() + "7");
        resetar = 0;
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        if(resetar == 1){
            TxtCalc.setText("");
        }
        TxtCalc.setText(TxtCalc.getText() + "8");
        resetar = 0;
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        if(resetar == 1){
            TxtCalc.setText("");
        }
        TxtCalc.setText(TxtCalc.getText() + "9");
        resetar = 0;
    }//GEN-LAST:event_Button9ActionPerformed

    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
        num1 = 0.0;
        num2 = 0;
        TxtCalc.setText("");
    }//GEN-LAST:event_ButtonCActionPerformed

    private void ButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSomaActionPerformed
        num1 = Double.parseDouble(TxtCalc.getText());
        operador = "+";
        resetar = 1;
    }//GEN-LAST:event_ButtonSomaActionPerformed

    private void ButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIgualActionPerformed
        num2 = Double.parseDouble(TxtCalc.getText());
        if(operador == "+"){
            TxtCalc.setText(String.valueOf(num1+num2));
        } 
        if(operador == "-"){
            TxtCalc.setText(String.valueOf(num1-num2));
        }
        if(operador == "x"){
            TxtCalc.setText(String.valueOf(num1*num2));
        }
        if(operador == "÷"){
            TxtCalc.setText(String.valueOf(num1/num2));
        }
        if(operador == "^"){
            TxtCalc.setText(String.valueOf(Math.pow(num1, num2)));
        }
        resetar = 1;
    }//GEN-LAST:event_ButtonIgualActionPerformed

    private void ButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubActionPerformed
        num1 = Double.parseDouble(TxtCalc.getText());
        operador = "-";
        resetar = 1;
    }//GEN-LAST:event_ButtonSubActionPerformed

    private void ButtonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiActionPerformed
        num1 = Double.parseDouble(TxtCalc.getText());
        operador = "x";
        resetar = 1;
    }//GEN-LAST:event_ButtonMultiActionPerformed

    private void ButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivActionPerformed
        num1 = Double.parseDouble(TxtCalc.getText());
        operador = "÷";
        resetar = 1;
    }//GEN-LAST:event_ButtonDivActionPerformed

    private void ButtonCeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCeActionPerformed
        TxtCalc.setText("");
    }//GEN-LAST:event_ButtonCeActionPerformed

    private void ButtonSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSqrtActionPerformed
        num1 = Double.parseDouble(TxtCalc.getText());
        TxtCalc.setText(String.valueOf(Math.sqrt(num1)));
        resetar = 1;
    }//GEN-LAST:event_ButtonSqrtActionPerformed

    private void ButtonPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPowActionPerformed
        num1 = Double.parseDouble(TxtCalc.getText());
        operador = "^";
        resetar = 1;
    }//GEN-LAST:event_ButtonPowActionPerformed

    private void ButtonNegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNegativeActionPerformed
        //Aqui está sendo tratado valores positivos ou negativos.
        num1 = Double.parseDouble(TxtCalc.getText());
        if(num1 > 0){
            num1 = num1 * -1;
        } else {
            num1 = Math.abs(num1);//
        }
        TxtCalc.setText(String.valueOf(num1));
    }//GEN-LAST:event_ButtonNegativeActionPerformed

    private void ButtonPorcentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPorcentoActionPerformed
        num2 = Double.parseDouble(TxtCalc.getText());
        double percentual = num2/100;
        if(operador == "+"){
            TxtCalc.setText(String.valueOf(num1+(num1*percentual)));
        } 
        if(operador == "-"){
            TxtCalc.setText(String.valueOf(num1-(num1*percentual)));
        }
        if(operador == "x"){
            TxtCalc.setText(String.valueOf(num1*percentual));
        }
        if(operador == "÷"){
            TxtCalc.setText(String.valueOf(num1/percentual));
        }
        resetar = 1;
    }//GEN-LAST:event_ButtonPorcentoActionPerformed

    private void ButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDotActionPerformed
        if(resetar == 1){
            TxtCalc.setText("");
        }
        TxtCalc.setText(TxtCalc.getText() + ".");
        resetar = 0;
    }//GEN-LAST:event_ButtonDotActionPerformed

    private void TemaClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemaClaroActionPerformed
        TemaEscuro.setSelected(false);
        jPanel1.setBackground(Color.WHITE);
        jPanel2.setBackground(Color.WHITE);
        LabelTitulo.setForeground(Color.BLACK);
        LabelCredito.setForeground(Color.BLACK);
    }//GEN-LAST:event_TemaClaroActionPerformed

    private void TemaEscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemaEscuroActionPerformed
        TemaClaro.setSelected(false);
        jPanel1.setBackground(Color.BLACK);
        jPanel2.setBackground(Color.BLACK);
        LabelTitulo.setForeground(Color.WHITE);
        LabelCredito.setForeground(Color.WHITE);
    }//GEN-LAST:event_TemaEscuroActionPerformed

    private void FonteTahomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FonteTahomaActionPerformed
        FonteArial.setSelected(false);
        LabelTitulo.setFont(new Font("Tahoma", Font.BOLD, 48));
        TxtCalc.setFont(new Font("Tahoma", Font.BOLD, 18));
        Button0.setFont(new Font("Tahoma", Font.BOLD, 18));
        Button1.setFont(new Font("Tahoma", Font.BOLD, 18));
        Button2.setFont(new Font("Tahoma", Font.BOLD, 18));
        Button3.setFont(new Font("Tahoma", Font.BOLD, 18));
        Button4.setFont(new Font("Tahoma", Font.BOLD, 18));
        Button5.setFont(new Font("Tahoma", Font.BOLD, 18));
        Button6.setFont(new Font("Tahoma", Font.BOLD, 18));
        Button7.setFont(new Font("Tahoma", Font.BOLD, 18));
        Button8.setFont(new Font("Tahoma", Font.BOLD, 18));
        Button9.setFont(new Font("Tahoma", Font.BOLD, 18));
        ButtonDot.setFont(new Font("Tahoma", Font.BOLD, 18));
        ButtonSub.setFont(new Font("Tahoma", Font.BOLD, 18));
        ButtonSoma.setFont(new Font("Tahoma", Font.BOLD, 18));
        ButtonDiv.setFont(new Font("Tahoma", Font.BOLD, 18));
        ButtonCe.setFont(new Font("Tahoma", Font.BOLD, 18));
        ButtonC.setFont(new Font("Tahoma", Font.BOLD, 18));
        ButtonMulti.setFont(new Font("Tahoma", Font.BOLD, 18));
        ButtonIgual.setFont(new Font("Tahoma", Font.BOLD, 18));
        ButtonPorcento.setFont(new Font("Tahoma", Font.BOLD, 18));
        ButtonNegative.setFont(new Font("Tahoma", Font.BOLD, 18));
        ButtonPow.setFont(new Font("Tahoma", Font.BOLD, 18));
        ButtonSqrt.setFont(new Font("Tahoma", Font.BOLD, 18));
        LabelCredito.setFont(new Font("Tahoma", Font.BOLD, 18));
    }//GEN-LAST:event_FonteTahomaActionPerformed

    private void FonteArialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FonteArialActionPerformed
        FonteTahoma.setSelected(false);
        LabelTitulo.setFont(new Font("Cambria", Font.BOLD, 48));
        TxtCalc.setFont(new Font("Cambria", Font.BOLD, 18));
        Button0.setFont(new Font("Cambria", Font.BOLD, 18));
        Button1.setFont(new Font("Cambria", Font.BOLD, 18));
        Button2.setFont(new Font("Cambria", Font.BOLD, 18));
        Button3.setFont(new Font("Cambria", Font.BOLD, 18));
        Button4.setFont(new Font("Cambria", Font.BOLD, 18));
        Button5.setFont(new Font("Cambria", Font.BOLD, 18));
        Button6.setFont(new Font("Cambria", Font.BOLD, 18));
        Button7.setFont(new Font("Cambria", Font.BOLD, 18));
        Button8.setFont(new Font("Cambria", Font.BOLD, 18));
        Button9.setFont(new Font("Cambria", Font.BOLD, 18));
        ButtonDot.setFont(new Font("Cambria", Font.BOLD, 18));
        ButtonSub.setFont(new Font("Cambria", Font.BOLD, 18));
        ButtonSoma.setFont(new Font("Cambria", Font.BOLD, 18));
        ButtonDiv.setFont(new Font("Cambria", Font.BOLD, 18));
        ButtonCe.setFont(new Font("Cambria", Font.BOLD, 18));
        ButtonC.setFont(new Font("Cambria", Font.BOLD, 18));
        ButtonMulti.setFont(new Font("Cambria", Font.BOLD, 18));
        ButtonIgual.setFont(new Font("Cambria", Font.BOLD, 18));
        ButtonPorcento.setFont(new Font("Cambria", Font.BOLD, 18));
        ButtonNegative.setFont(new Font("Cambria", Font.BOLD, 18));
        ButtonPow.setFont(new Font("Cambria", Font.BOLD, 18));
        ButtonSqrt.setFont(new Font("Cambria", Font.BOLD, 18));
        LabelCredito.setFont(new Font("Cambria", Font.BOLD, 18));
    }//GEN-LAST:event_FonteArialActionPerformed

    private void ButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDelActionPerformed
        String num = TxtCalc.getText();
        TxtCalc.setText("");
        for( int i = 0; i < num.length()-1; i++ ){
            TxtCalc.setText(TxtCalc.getText() + num.charAt(i));
        }
    }//GEN-LAST:event_ButtonDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonCe;
    private javax.swing.JButton ButtonDel;
    private javax.swing.JButton ButtonDiv;
    private javax.swing.JButton ButtonDot;
    private javax.swing.JButton ButtonIgual;
    private javax.swing.JButton ButtonMulti;
    private javax.swing.JButton ButtonNegative;
    private javax.swing.JButton ButtonPorcento;
    private javax.swing.JButton ButtonPow;
    private javax.swing.JButton ButtonSoma;
    private javax.swing.JButton ButtonSqrt;
    private javax.swing.JButton ButtonSub;
    private javax.swing.JCheckBoxMenuItem FonteArial;
    private javax.swing.JCheckBoxMenuItem FonteTahoma;
    private javax.swing.JLabel LabelCredito;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenu MenuTema;
    private javax.swing.JCheckBoxMenuItem TemaClaro;
    private javax.swing.JCheckBoxMenuItem TemaEscuro;
    private javax.swing.JMenu TemaFontes;
    private javax.swing.JTextField TxtCalc;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
